# Generated by Django 3.2.9 on 2021-12-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poketype', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('ability', models.CharField(max_length=100)),
            ],
        ),
    ]
