# Generated by Django 3.2.9 on 2021-12-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211210_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armor',
            old_name='main_stat',
            new_name='main_stats',
        ),
    ]
